Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -33,15 +33,17 @@ jobs:
       run: |
          python3 ceoban.py || { echo "ceoban.py failed"; exit 1; }
          python3 kfc.py || { echo "kfc.py failed"; exit 1; }
-         python3 mac.py || { echo "mac.py failed"; exit 1; }
-         python3 lotte.py || { echo "lotte.py failed"; exit 1; }
+         # python3 mac.py || { echo "mac.py failed"; exit 1; }
+         # python3 lotte.py || { echo "lotte.py failed"; exit 1; }
         
     - name: Add and commit changes
       run: |
         git config --global user.email "sdw10195@gmail.com"
         git config --global user.name "seodaewon1"
-        git add kfc/*.json lotte/*.json macdonald/*.json || echo "No files to add"
-        if ! git diff-index --quiet HEAD; then
+        git add ceoban/ceoban_*.json
+        git add kfc/kfc_*.json
+
+        
           git commit -m "차트 수집 완료"
         else
           echo "No changes to commit"
