Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -1,15 +1,18 @@
+# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
+
 name: Python package
 
 on:
   push:
-    branches: ["main"]
+    branches: [ "main" ]
   pull_request:
-    branches: ["main"]
+    branches: [ "main" ]
   schedule:
     - cron: '30 1 * * *'
-
 jobs:
   build:
+
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -19,39 +22,44 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
+      uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager
+        pip install requests
+        pip install beautifulsoup4
+        pip install lxml
+        pip install pandas
+        pip install selenium
+        pip install webdriver_manager
         
     - name: Install Google Chrome
       run: |
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install
+        sudo dpkg -i google-chrome-stable_current_amd64.deb
+        sudo apt-get -f install
         
     - name: Run Python scripts
       run: |
          python3 ceoban.py || { echo "ceoban.py failed"; exit 1; }
          python3 kfc.py || { echo "kfc.py failed"; exit 1; }
-         ls -la ceoban/
-         ls -la kfc/
-         # ls -la lotte/
-         # ls -la macdonald/
+         python3 mac.py || { echo "mac.py failed"; exit 1; }
+         python3 lotte.py || { echo "lotte.py failed"; exit 1; }
         
-    - name: Commit and Push
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
+    - name: Commits
+      run : |
         git config --global user.email "sdw10195@gmail.com"
         git config --global user.name "seodaewon1"
         git add ceoban/ceoban_*.json
         git add kfc/kfc_*.json
-        # git add lotte/lotte_*.json
-        # git add macdonald/macdonald_*.json
+        git add lotte/lotte_*.json
+        git add macdonald/macdonald_*.json
         
-        git status
-        git commit -m "차트 수집 완료" || echo "No changes to commit"
-        git push origin main
+        git commit -m "차트 수집 완료"
+    - name: Push
+      uses: ad-m/github-push-action@master
+      with:
+        branch: "main"
+        github_token: ${{ secrets.GITHUB_TOKEN }}
