Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -1,6 +1,3 @@
-# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
 name: Python package
 
 on:
@@ -10,9 +7,9 @@ on:
     branches: [ "main" ]
   schedule:
     - cron: '30 1 * * *'
+
 jobs:
   build:
-
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -28,12 +25,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install requests
-        pip install beautifulsoup4
-        pip install lxml
-        pip install pandas
-        pip install selenium
-        pip install webdriver_manager
+        pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager
         
     - name: Install Google Chrome
       run: |
@@ -43,20 +35,20 @@ jobs:
         
     - name: Run Python scripts
       run: |
-         python3 ceoban.py || { echo "ceoban.py failed"; exit 1; }
-         python3 kfc.py || { echo "kfc.py failed"; exit 1; }
-         python3 mac.py || { echo "mac.py failed"; exit 1; }
-         python3 lotte.py || { echo "lotte.py failed"; exit 1; }
+        python3 ceoban.py > ceoban.log || { echo "ceoban.py failed"; exit 1; }
+        python3 kfc.py > kfc.log || { echo "kfc.py failed"; exit 1; }
+        python3 mac.py > mac.log || { echo "mac.py failed"; exit 1; }
+        python3 lotte.py > lotte.log || { echo "lotte.py failed"; exit 1; }
         
     - name: Commits
-      run : |
+      run: |
         git config --global user.email "sdw10195@gmail.com"
         git config --global user.name "seodaewon1"
         git add ceoban/ceoban_*.json
         git add lotte/lotte_*.json
         git add macdonald/macdonald_*.json
         
-        git commit -m "차트 수집 완료"
+        git commit -m "차트 수집 완료" || echo "No changes to commit"
     - name: Push
       uses: ad-m/github-push-action@master
       with:
