Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -22,40 +22,41 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager
-        
+
     - name: Install Google Chrome
       run: |
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
         sudo dpkg -i google-chrome-stable_current_amd64.deb
         sudo apt-get -f install
-        
+
     - name: Run Python scripts
       run: |
         python3 ceoban.py > ceoban.log || { echo "ceoban.py failed"; exit 1; }
-        python3 kfc.py > kfc.log || { echo "kfc.py failed"; exit 1; }
-        python3 mac.py > mac.log || { echo "mac.py failed"; exit 1; }
-        python3 lotte.py > lotte.log || { echo "lotte.py failed"; exit 1; }
-        
+        # python3 kfc.py > kfc.log || { echo "kfc.py failed"; exit 1; }
+        # python3 mac.py > mac.log || { echo "mac.py failed"; exit 1; }
+        # python3 lotte.py > lotte.log || { echo "lotte.py failed"; exit 1; }
+
     - name: Pull changes
       run: |
         git pull origin main
-        
+
     - name: Commits
       run: |
         git config --global user.email "sdw10195@gmail.com"
         git config --global user.name "seodaewon1"
-        
+
         git add ceoban/ceoban_*.json
-        git add lotte/lotte_*.json
-        git add kfc/kfc_*.json
-        git add macdonald/macdonald_*.json
-        
+        # git add lotte/lotte_*.json
+        # git add kfc/kfc_*.json
+        # git add macdonald/macdonald_*.json
+
         git commit -m "차트 수집 완료" || echo "No changes to commit"
-        
+
     - name: Push
       uses: ad-m/github-push-action@master
       with:
